Fixes Issue#103 Navbar on index.php(Home Page) enhanced.
Spectrum-CETB/LesKollab pull request #107
Opened 2021-04-22 02:46 UTC by hardikvarshney

INCLUDE ALL NECESSARY FIELDS AND DELETE FIELDS THAT ARE NOT NECESSARY.

### Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

2021-04-22 03:09 UTC, hardikvarshney commented
@rupeshmohanty Please mention the level of the issue(i.e. level 2) on this PR and kindly review it.

2021-04-22 12:45 UTC, ishubham21 requested changes
I think that the sign-in icon looks quite odd since it's the only icon present on the page, making the home page less pleasing plus violating the uniformity. 
It would be better if we could just remove the same. What do others say?

2021-04-22 13:03 UTC, hardikvarshney commented
> I think that the sign-in icon looks quite odd since it's the only icon present on the page, making the home page less pleasing plus violating the uniformity.
> It would be better if we could just remove the same. What do others say?

@ishubham21 Requested change done. You can now review.

2021-04-22 13:03 UTC, ishubham21 approved these changes

2021-04-23 00:00 UTC, anika-001 approved these changes

2021-04-23 12:26 UTC, sakshi300699 approved these changes

2021-04-23 14:55 UTC, merged